/*
==================================================================================
PROJETO: ANALYTICS DE PERFORMANCE DE VENDAS (RCA)
AUTOR: Renan G. Azanha
SISTEMA: Oracle SQL (ERP Winthor)
DESCRIÇÃO: 
    Query de alta performance para consolidação de KPIs comerciais.
    Foco: Vendas, Margem, Cobertura, Inadimplência e CRM (Churn/Reativação).
==================================================================================
*/

WITH
-- ============================================================================
-- 1. DEFINIÇÃO DE PERÍODO E CALENDÁRIO
-- ============================================================================
PERIODO_ANALISE AS (
    SELECT DATA,
           TO_CHAR(DATA, 'MM') AS MES,
           TO_CHAR(DATA, 'YYYY') AS ANO,
           TO_CHAR(DATA, 'MM-YYYY') AS MES_ANO, -- Corrigido: Coluna necessária para agrupamento
           MIN(DATA) OVER() AS DT_INI,
           MAX(DATA) OVER() AS DT_FIM
    FROM PCDATAS
    -- ⚠️ ATENÇÃO: Garanta que existe venda nestas datas no seu banco
    WHERE DATA BETWEEN TO_DATE('01-11-2025', 'DD-MM-YYYY') AND TO_DATE('30-11-2025', 'DD-MM-YYYY')
),

-- ============================================================================
-- 2. INTELIGÊNCIA DE CRM (REACTIVAÇÃO E CHURN)
-- ============================================================================

DT_CORTE_REACT AS (
    SELECT MIN(DATA) - 90 AS DT_LIMITE FROM PERIODO_ANALISE
),

HIST_COMPRA_ANT AS (
    SELECT CODCLI, MAX(DATA) AS DT_ULT_COMPRA
    FROM PCPEDC
    WHERE DATA < (SELECT MIN(DATA) FROM PERIODO_ANALISE)
    AND CONDVENDA IN (1,2,3,7,9,14,15,17,18,19,98) 
    GROUP BY CODCLI
),

VENDAS_VAL_REACT AS (
    SELECT CODCLI, CODUSUR
    FROM PCPEDC
    WHERE DATA BETWEEN (SELECT MIN(DATA) FROM PERIODO_ANALISE) AND (SELECT MAX(DATA) FROM PERIODO_ANALISE)
      AND CONDVENDA IN (1,2,3,7,9,14,15,17,18,19,98)
    GROUP BY CODCLI, CODUSUR
    HAVING SUM(VLTOTAL) >= 150
),

CLI_NOVOS_PER AS (
    SELECT CODCLI FROM PCCLIENT 
    WHERE TRUNC(DTCADASTRO) BETWEEN (SELECT MIN(DATA) FROM PERIODO_ANALISE) AND (SELECT MAX(DATA) FROM PERIODO_ANALISE)
),

REACT_RCA_AGG AS (
    SELECT VV.CODUSUR, PA.MES, PA.ANO, COUNT(DISTINCT VV.CODCLI) AS QTD_REATIVADOS
    FROM VENDAS_VAL_REACT VV
    JOIN PCCLIENT C ON C.CODCLI = VV.CODCLI
    LEFT JOIN HIST_COMPRA_ANT HIST ON HIST.CODCLI = VV.CODCLI
    CROSS JOIN DT_CORTE_REACT DC
    CROSS JOIN (SELECT DISTINCT MES, ANO FROM PERIODO_ANALISE) PA
    WHERE C.DTEXCLUSAO IS NULL
      AND C.BLOQUEIO = 'N'
      AND NOT EXISTS (SELECT 1 FROM CLI_NOVOS_PER CN WHERE CN.CODCLI = VV.CODCLI)
      AND (HIST.DT_ULT_COMPRA IS NULL OR HIST.DT_ULT_COMPRA < DC.DT_LIMITE)
    GROUP BY VV.CODUSUR, PA.MES, PA.ANO
),

-- ============================================================================
-- 3. VENDAS E METAS
-- ============================================================================

VENDEDORES_ATIVOS AS (
    SELECT CODUSUR, TO_CHAR(DATA, 'MM') AS MES, TO_CHAR(DATA, 'YYYY') AS ANO
    FROM PCMETARCA 
    WHERE DATA IN (SELECT DATA FROM PERIODO_ANALISE) AND (VLVENDAPREV > 0 OR NUMCLIPOS > 0)
    UNION
    SELECT PCPEDC.CODUSUR, TO_CHAR(PCPEDI.DATA, 'MM'), TO_CHAR(PCPEDI.DATA, 'YYYY')
    FROM PCPEDC JOIN PCPEDI ON PCPEDC.NUMPED = PCPEDI.NUMPED
    WHERE PCPEDI.DATA IN (SELECT DATA FROM PERIODO_ANALISE)
),

METAS_AGG AS (
    SELECT V.CODUSUR, V.MES, V.ANO, 
           SUM(NVL(M.VLVENDAPREV, 0)) AS META_VENDA, 
           SUM(NVL(M.NUMCLIPOS, 0)) AS META_COBERTURA
    FROM VENDEDORES_ATIVOS V
    LEFT JOIN PCMETARCA M ON M.CODUSUR = V.CODUSUR 
         AND TO_CHAR(M.DATA, 'MM') = V.MES AND TO_CHAR(M.DATA, 'YYYY') = V.ANO
    GROUP BY V.CODUSUR, V.MES, V.ANO
),

VENDAS_POR_VENDEDOR AS (
    SELECT PCPEDC.CODUSUR, PA.MES, PA.ANO,
        SUM(ROUND(DECODE(PCPEDC.CONDVENDA, 5, 0, 6, 0, 11, 0, 12, 0, 
            1, DECODE(NVL(PCPEDI.BONIFIC,'X'), 'F', 0, (NVL(PCPEDI.PVENDA,0) + NVL(PCPEDI.VLOUTRASDESP,0)) * NVL(PCPEDI.QT,0)), 
            (NVL(PCPEDI.PVENDA,0) + NVL(PCPEDI.VLOUTRASDESP,0)) * NVL(PCPEDI.QT,0)), 2)) AS VENDA_REAL,
            
        SUM(NVL(PCPEDI.VLCUSTOREAL, 0) * NVL(PCPEDI.QT, 0)) AS CMV,
        
        ROUND((SUM(NVL(PCPEDC.PRAZOMEDIO, 0) * NVL(PCPEDI.QT, 0) * NVL(PCPEDI.PVENDA, 0)) / 
               NULLIF(SUM(NVL(PCPEDI.QT, 0) * NVL(PCPEDI.PVENDA, 0)), 0)), 2) AS PRAZO_MEDIO
    FROM PCPEDC 
    JOIN PCPEDI ON PCPEDC.NUMPED = PCPEDI.NUMPED 
    JOIN PERIODO_ANALISE PA ON PCPEDI.DATA = PA.DATA
    WHERE PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
    GROUP BY PCPEDC.CODUSUR, PA.MES, PA.ANO
),

DIAS_UTEIS AS (
    SELECT MES_ANO, 
           COUNT(DISTINCT DATA) AS TOTAL_DIAS,
           COUNT(DISTINCT CASE WHEN DATA <= TRUNC(SYSDATE) THEN DATA END) AS DIAS_PASSADOS,
           MES, ANO 
    FROM PERIODO_ANALISE 
    WHERE DATA IN (SELECT DATA FROM PCDATAS WHERE DIAUTIL = 'S') 
    GROUP BY MES_ANO, MES, ANO
),

COBERTURA AS (
    SELECT PED.CODUSUR, PA.MES, PA.ANO, COUNT(DISTINCT PED.CODCLI) AS QTD_CLIENTES_COBERTURA
    FROM PCPEDC PED 
    JOIN PERIODO_ANALISE PA ON PED.DATA = PA.DATA 
    WHERE PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
    GROUP BY PED.CODUSUR, PA.MES, PA.ANO
),

INADIMPLENCIA AS (
    SELECT P.CODUSUR, SUM(P.VALOR) AS VALOR_EM_ABERTO
    FROM PCPREST P 
    WHERE P.DTVENCORIG <= SYSDATE - 5 
      AND P.DTPAG IS NULL 
      AND P.CODCOB NOT IN ('BNF', 'DEV', 'PERD', 'C', 'CH') 
    GROUP BY P.CODUSUR
)

-- ============================================================================
-- 4. RELATÓRIO FINAL
-- ============================================================================
SELECT
    RB.ANO,
    RB.MES,
    RB.CODUSUR AS COD_RCA,
    REGEXP_SUBSTR(PCUSUARI.NOME, '^\S+') AS NOME_RCA,
    
    NVL(M.META_VENDA, 0) AS META_VENDA,
    NVL(VV.VENDA_REAL, 0) AS VENDA_REALIZADA,
    
    ROUND(CASE WHEN NVL(M.META_VENDA, 0) = 0 THEN 0 
          ELSE (NVL(VV.VENDA_REAL, 0) / M.META_VENDA) * 100 END, 2) AS PCT_ATINGIMENTO,
          
    ROUND((NVL(VV.VENDA_REAL, 0) / NULLIF(DU.DIAS_PASSADOS, 0)) * NVL(DU.TOTAL_DIAS, 0), 2) AS PROJECAO_FECHAMENTO,
    
    ROUND(CASE WHEN NVL(VV.VENDA_REAL, 0) = 0 THEN 0 
          ELSE (NVL(VV.VENDA_REAL,0) - NVL(VV.CMV,0)) / NULLIF(NVL(VV.VENDA_REAL,0),0) * 100 END, 2) AS MARGEM_LUCRO,
    
    NVL(M.META_COBERTURA, 0) AS META_POSITIVACAO,
    NVL(COB.QTD_CLIENTES_COBERTURA, 0) AS CLIENTES_ATENDIDOS,
    
    NVL(R.QTD_REATIVADOS, 0) AS CLIENTES_RECUPERADOS,
    NVL(INA.VALOR_EM_ABERTO, 0) AS CARTEIRA_INADIMPLENTE

FROM VENDEDORES_ATIVOS RB
JOIN PCUSUARI ON PCUSUARI.CODUSUR = RB.CODUSUR
LEFT JOIN METAS_AGG M ON M.CODUSUR = RB.CODUSUR AND M.MES = RB.MES AND M.ANO = RB.ANO
LEFT JOIN VENDAS_POR_VENDEDOR VV ON VV.CODUSUR = RB.CODUSUR AND VV.MES = RB.MES AND VV.ANO = RB.ANO
LEFT JOIN DIAS_UTEIS DU ON DU.MES = RB.MES AND DU.ANO = RB.ANO
LEFT JOIN COBERTURA COB ON COB.CODUSUR = RB.CODUSUR AND COB.MES = RB.MES AND COB.ANO = RB.ANO
LEFT JOIN REACT_RCA_AGG R ON R.CODUSUR = RB.CODUSUR AND R.MES = RB.MES AND R.ANO = RB.ANO
LEFT JOIN INADIMPLENCIA INA ON INA.CODUSUR = RB.CODUSUR

ORDER BY RB.ANO DESC, RB.MES DESC, PCT_ATINGIMENTO DESC